server:
   port: 9103
#   contextPath: /uaa
spring:
   application:
      name: iscp-authserver
   cloud:
      nacos:
         discovery:
            server-addr: 127.0.0.1:8848
            namespace: c6ef4ed4-1a37-4672-a8dc-53926e8e9b49
logging:
   level:
      root: INFO
      org.springframework.security: DEBUG
management:
   endpoints:
      web:
         exposure:
            include: '*'