apiVersion: v1
kind: Pod
metadata:
  name: iscp-nacos-pod
spec:
  containers:
    - image: 192.168.99.103:5000/iscp-nacos
      imagePullPolicy: IfNotPresent
      name: iscp-nacos-mike
      ports:
      - containerPort: 9100
        protocol: TCP