server:
   port: 9102
spring:
   application:
      name: iscp-gateway-sentinel
   cloud:
      nacos:
         discovery:
            server-addr: 127.0.0.1:8848
            namespace: c6ef4ed4-1a37-4672-a8dc-53926e8e9b49
      gateway:
         enabled: true
         discovery:
            locator:
               lower-case-service-id: true
         routes:
         -  id: iscp-nacos
            uri: lb://iscp-nacos
            predicates:
            - Path=/nacos/**
            filters:
            - StripPrefix=1
         -  id: iscp-feign-sentinel
            uri: lb://iscp-feign-sentinel
            predicates:
            - Path=/feign/**
            filters:
            - StripPrefix=1
      sentinel:
         datasource.ds1.nacos:
            server-addr: 127.0.0.1:8848
            namespace: c6ef4ed4-1a37-4672-a8dc-53926e8e9b49
            data-id: iscp-gateway-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            ruleType: gw-flow
         transport:
            dashboard: localhost:28080
         filter:
            enabled: true
management:
   endpoints:
      web:
         exposure:
            include: '*'