server:
   port: 9100
spring:
   application:
      name: iscp-nacos
   cloud:
      nacos:
         discovery:
            server-addr: 192.168.99.1:8848
            namespace: c6ef4ed4-1a37-4672-a8dc-53926e8e9b49
management:
   endpoints:
      web:
         exposure:
            include: '*'
logging:
  level:
    root: INFO
    com.island.iscp.nacos: DEBUG