server:
   port: 9100
spring:
   application:
      name: iscp-nacos
   cloud:
      nacos:
         discovery:
            server-addr: 127.0.0.1:8848
management:
   endpoints:
      web:
         exposure:
            include: '*'