server:
   port: 9101
spring:
   application:
      name: iscp-feign-sentinel
   cloud:
      nacos:
         discovery:
            server-addr: 192.168.99.1:8848
            namespace: c6ef4ed4-1a37-4672-a8dc-53926e8e9b49
      sentinel:
         datasource.ds1.nacos:
            server-addr: 192.168.99.1:8848
            namespace: c6ef4ed4-1a37-4672-a8dc-53926e8e9b49
            data-id: iscp-feign-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            ruleType: degrade
         transport:
            dashboard: 192.168.99.1:28080
management:
   endpoints:
      web:
         exposure:
            include: '*'
feign:
   sentinel:
      enabled: true
